# Generated by Django 4.2.6 on 2023-10-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('setting', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=10)),
                ('gender', models.CharField(default='Не указано', max_length=10)),
                ('birthdate', models.CharField(default='Не указано', max_length=5)),
                ('about', models.CharField(default='Отсутствует', max_length=10)),
                ('guilds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.guilds')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='tests/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.BigIntegerField()),
                ('type', models.SmallIntegerField()),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('guilds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.guilds')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('guilds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.guilds')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discord.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.BigIntegerField()),
                ('reaction', models.CharField(max_length=30)),
                ('type', models.SmallIntegerField()),
                ('object', models.BigIntegerField()),
                ('guilds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.guilds')),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.IntegerField()),
                ('voice', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('lvl', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('up_xp', models.IntegerField(default=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.user'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('guilds', 'user')},
        ),
    ]
